### ISSUE TITLE
"Escape hammering" video reset results in division by zero

### ISSUE THREAD

**Issue by olofson** [olofson/koboredux#442]
Something is broken in the emergency video mode reset feature.
```
Thread 1 "kobord" received signal SIGFPE, Arithmetic exception.
0x0000000000444bc4 in windowbase_t::width (this=0xb61c60) at /home/david/src/koboredux/src/gfxengine/window.h:380
380		int width()	{ return px2() - px(); }
(gdb) bt
#0  0x0000000000444bc4 in windowbase_t::width (this=0xb61c60) at /home/david/src/koboredux/src/gfxengine/window.h:380
#1  KOBO_GridTFX::Render (this=this@entry=0x6c7bc0 <KOBO_screen::gridtfx>) at /home/david/src/koboredux/src/gridtfx.cpp:123
#2  0x000000000043e9dd in KOBO_screen::render_fx () at /home/david/src/koboredux/src/screen.cpp:1085
#3  0x000000000043ed2e in kobo_basestate_t::post_render (this=this@entry=0x6da6e0 <st_error>) at /home/david/src/koboredux/src/states.cpp:83
#4  0x00000000004400f8 in st_error_t::post_render (this=0x6da6e0 <st_error>) at /home/david/src/koboredux/src/states.cpp:1419
#5  0x00000000004378ce in gamestatemanager_t::post_render (this=<optimized out>) at /home/david/src/koboredux/src/gamestate.cpp:282
#6  0x0000000000428f39 in kobo_gfxengine_t::post_render (this=<optimized out>) at /home/david/src/koboredux/src/kobo.cpp:2300
#7  0x000000000044dc10 in gfxengine_t::present (this=0x6f32a0) at /home/david/src/koboredux/src/gfxengine/gfxengine.cpp:1285
#8  0x000000000042231a in dashboard_window_t::update (this=this@entry=0x23e20c0, force=force@entry=true) at /home/david/src/koboredux/src/dashboard.cpp:129
#9  0x000000000042274e in dashboard_window_t::mode (this=0x23e20c0, m=m@entry=DASHBOARD_BLACK, tr=tr@entry=DASHBOARD_INSTANT)
    at /home/david/src/koboredux/src/dashboard.cpp:241
#10 0x000000000042b46b in KOBO_main::init_display (p=0x6eded0) at /home/david/src/koboredux/src/kobo.cpp:890
#11 0x000000000042bca1 in KOBO_main::restart_video () at /home/david/src/koboredux/src/kobo.cpp:1452
#12 0x000000000042c272 in KOBO_main::run () at /home/david/src/koboredux/src/kobo.cpp:1551
#13 0x000000000042d87f in main (argc=<optimized out>, argv=<optimized out>) at /home/david/src/koboredux/src/kobo.cpp:2743
```
The windowbase_t instance has zeros in all fields here.

**Comment by olofson** [comment]
Only happens with the "redux" theme! It still works fine with the "mono" theme here, as of 435245881dcdf7fdb45d9a8b9d787889295ad8f8 at least.
